osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 10
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- |
  npm run build
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    npm run release:mac
  else
    npm run release:linux
    npm run release:win
  fi
branches:
  except:
  - "/^(?!v\\d+\\.\\d+\\.\\d+(-beta\\.\\d+)?).+$/"
deploy:
  provider: releases
  api_key:
    secure: "LJU+NLhWS8yCBR9TMnPg0aMI618zZpW1+v297nk5O3xxbJnMxV4usIl+Yi+3o0sUDn/xevfFV2nQe7EPRsjQxetVHsseuH/mr/9cAcOVcf7rUoQGI1ZU+M5RPgNz4P4kPGlao/9nzaCqasGWdYLIk+FCU8eus4zGPl5S8e1yWoP8C3cfpyWVAe/tTNvQeKh5G7t9PKlb53pnIJM65VKuxrJ3wZQPdutUortdCDuhnnED20kJljZaww/HpdtOhVSyGeVLYotQd00bb+mNWqWcdxj3uGxU15R57Rnj+Lz3IGgFBEHJNCmgRedSecVMLpi943N6aTLKGKolHasIcgSdFOH0riMlZlDNyn3XKEkAcFoqVG6PhY22fXPXkdiXcaFC5mWUJuLwSFDoxafVZo5NznrBl/4wfXlrfE/osZ3B4NRiw7RustCLZ9vvj1a7cglxj5gFmxlZgM9vnn7zEBP/nOyJMV4tQGcB0xHz3fXsEcE9i4PCnWYvG/2RezS7/2fNWsRLcFAT0WgAkfiKmX1saiafXuf7ncOfzOCbpaVJ2Dge8hfhnLrwXXhdE9VL3eaSP3f0bGQ5dhDqVrg6Hf4xjfFB/knzuMBrTT8v9g+z6AEsYHvOyI2pI+Ua5VLSqIXwRrAUDFCOLYxL/azAM2DxMHHbQM0PYXgfIMeUJFktWi8="
  cleanup: false
  file_glob: true
  file:
    - releases/*.dmg
    - releases/*.zip
    - releases/*.tar.gz
    - releases/*.exe
  on:
    tags: true
    repo: Shyked/yeelight-screen-sync
